version: "3"

services:
  api:
    build: ./api
    ports: 
      - "3000:3000"
    volumes:
      - ./api:/code
  app:
    build: ./app
    depends_on: 
      - api
    ports: 
      - "3001:3001"
    environment:
      - BASE_URL=api:3000
    volumes:
      - ./app:/code
